export const navItems = [];

export const categories = [
  {
    id: "bearings",
    name: "Bearings",
    count: 2145,
    description: "Rolling and mounted bearing components for precision motion systems.",
    icon: "BR",
    tone: "from-orange-400 to-amber-500",
  },
  {
    id: "fasteners",
    name: "Fasteners",
    count: 3520,
    description: "Bolts, washers, and joining hardware for equipment assembly.",
    icon: "FS",
    tone: "from-sky-400 to-blue-600",
  },
  {
    id: "linear-motion",
    name: "Linear Motion",
    count: 967,
    description: "Guide rails and ball screws for repeatable positioning systems.",
    icon: "LM",
    tone: "from-violet-400 to-indigo-600",
  },
  {
    id: "pneumatic-components",
    name: "Pneumatic Components",
    count: 1238,
    description: "Air cylinders and valves for factory automation lines.",
    icon: "PN",
    tone: "from-cyan-400 to-teal-500",
  },
  {
    id: "electrical-components",
    name: "Electrical Components",
    count: 2765,
    description: "Industrial power, switching, and control accessories.",
    icon: "EL",
    tone: "from-amber-400 to-orange-500",
  },
  {
    id: "tools",
    name: "Tools",
    count: 812,
    description: "Maintenance and assembly tools for production teams.",
    icon: "TL",
    tone: "from-rose-400 to-orange-500",
  },
  {
    id: "aluminum-frames",
    name: "Aluminum Frames",
    count: 408,
    description: "Profiles and brackets for modular machine structures.",
    icon: "AF",
    tone: "from-slate-300 to-slate-500",
  },
  {
    id: "sensors",
    name: "Sensors",
    count: 1446,
    description: "Detection and measurement sensors for automated systems.",
    icon: "SN",
    tone: "from-emerald-400 to-teal-600",
  },
  {
    id: "automation-parts",
    name: "Automation Parts",
    count: 691,
    description: "Control and motion accessories for modern machine design.",
    icon: "AT",
    tone: "from-blue-400 to-indigo-600",
  },
];

function createProduct(config) {
  const defaultVariant = config.variants[0];

  return {
    id: config.id,
    categoryId: config.categoryId,
    name: config.name,
    type: config.type,
    brand: config.brand,
    stock: config.stock,
    availability: config.availability,
    image: config.image,
    description: config.description,
    spec: defaultVariant.spec,
    sku: defaultVariant.sku,
    price: defaultVariant.price,
    selectors: config.selectors,
    variants: config.variants,
  };
}

function variant({
  sku,
  price,
  spec,
  optionValues,
  stock,
  note,
  modelShape,
  modelColor,
  modelAccent,
  modelScale = 1,
}) {
  return {
    sku,
    price,
    spec,
    optionValues,
    stock,
    note,
    modelShape,
    modelColor,
    modelAccent,
    modelScale,
  };
}

export const products = [
  createProduct({
    id: "br-6204",
    categoryId: "bearings",
    name: "Deep Groove Bearing 6204-2RS",
    description: "General-purpose ball bearing for motors, pulleys, and compact rotating assemblies.",
    type: "Ball Bearing",
    brand: "FIBO Motion",
    stock: "In stock",
    availability: "in-stock",
    image: "BR",
    selectors: [
      { key: "innerDiameter", label: "Inner Diameter d", options: ["15 mm", "20 mm", "25 mm"] },
      { key: "sealType", label: "Seal Type", options: ["Open", "ZZ", "2RS"] },
      { key: "material", label: "Material", options: ["Chrome Steel", "Stainless"] },
    ],
    variants: [
      variant({ sku: "BR-6202-OPEN-CS", price: 180, spec: "15 x 35 x 11 mm open bearing for low-friction rotation.", optionValues: { innerDiameter: "15 mm", sealType: "Open", material: "Chrome Steel" }, stock: "In stock", note: "Lowest friction for protected housings.", modelShape: "torus", modelColor: "#94a3b8", modelAccent: "#e2e8f0", modelScale: 0.95 }),
      variant({ sku: "BR-6204-ZZ-CS", price: 320, spec: "20 x 47 x 14 mm shielded bearing for standard industrial use.", optionValues: { innerDiameter: "20 mm", sealType: "ZZ", material: "Chrome Steel" }, stock: "In stock", note: "Balanced option for dust protection and speed.", modelShape: "torus", modelColor: "#64748b", modelAccent: "#cbd5e1", modelScale: 1 }),
      variant({ sku: "BR-6205-2RS-SS", price: 490, spec: "25 x 52 x 15 mm sealed stainless bearing for corrosive environments.", optionValues: { innerDiameter: "25 mm", sealType: "2RS", material: "Stainless" }, stock: "Limited stock", note: "Recommended for washdown or humid conditions.", modelShape: "torus", modelColor: "#0f172a", modelAccent: "#38bdf8", modelScale: 1.05 }),
    ],
  }),
  createProduct({
    id: "br-pillow",
    categoryId: "bearings",
    name: "Pillow Block Unit UCP205",
    description: "Mounted bearing unit for shafts in conveyors and rotating fixtures.",
    type: "Bearing Unit",
    brand: "AxisPro",
    stock: "In stock",
    availability: "in-stock",
    image: "PU",
    selectors: [
      { key: "shaftSize", label: "Shaft Size", options: ["20 mm", "25 mm", "30 mm"] },
      { key: "housingMaterial", label: "Housing Material", options: ["Cast Iron", "Ductile Iron"] },
      { key: "insertType", label: "Insert Lock", options: ["Set Screw", "Eccentric Collar"] },
    ],
    variants: [
      variant({ sku: "UCP204-CI-SS", price: 760, spec: "20 mm mounted bearing in cast iron housing with set-screw insert.", optionValues: { shaftSize: "20 mm", housingMaterial: "Cast Iron", insertType: "Set Screw" }, stock: "In stock", note: "Compact choice for medium-duty frames.", modelShape: "box", modelColor: "#475569", modelAccent: "#f59e0b", modelScale: 1 }),
      variant({ sku: "UCP205-CI-EC", price: 890, spec: "25 mm mounted bearing with eccentric collar for conveyor duty.", optionValues: { shaftSize: "25 mm", housingMaterial: "Cast Iron", insertType: "Eccentric Collar" }, stock: "In stock", note: "Stable grip for unidirectional rotation.", modelShape: "box", modelColor: "#334155", modelAccent: "#60a5fa", modelScale: 1.08 }),
      variant({ sku: "UCP206-DI-SS", price: 1090, spec: "30 mm heavy-duty unit with ductile iron body and set-screw insert.", optionValues: { shaftSize: "30 mm", housingMaterial: "Ductile Iron", insertType: "Set Screw" }, stock: "Preorder", note: "Higher shock resistance for rugged machines.", modelShape: "box", modelColor: "#1e293b", modelAccent: "#22c55e", modelScale: 1.12 }),
    ],
  }),
  createProduct({
    id: "fs-m8",
    categoryId: "fasteners",
    name: "Hex Socket Bolt M8 x 30",
    description: "High-strength socket head bolt for machines, brackets, and rigid joints.",
    type: "Bolt",
    brand: "TorqueX",
    stock: "In stock",
    availability: "in-stock",
    image: "M8",
    selectors: [
      { key: "threadSize", label: "Thread Size", options: ["M6", "M8", "M10"] },
      { key: "length", label: "Length", options: ["20 mm", "30 mm", "40 mm"] },
      { key: "finish", label: "Finish", options: ["Black Oxide", "Zinc Plated"] },
    ],
    variants: [
      variant({ sku: "HSB-M6-20-BO", price: 9, spec: "M6 black-oxide socket bolt for compact fixture assemblies.", optionValues: { threadSize: "M6", length: "20 mm", finish: "Black Oxide" }, stock: "In stock", note: "Compact length for dense assemblies.", modelShape: "cylinder", modelColor: "#0f172a", modelAccent: "#f97316", modelScale: 0.92 }),
      variant({ sku: "HSB-M8-30-BO", price: 14, spec: "M8 x 30 black-oxide bolt, grade 12.9, for machine structures.", optionValues: { threadSize: "M8", length: "30 mm", finish: "Black Oxide" }, stock: "In stock", note: "General-purpose structural fastening option.", modelShape: "cylinder", modelColor: "#1e293b", modelAccent: "#38bdf8", modelScale: 1 }),
      variant({ sku: "HSB-M10-40-ZP", price: 22, spec: "M10 zinc-plated socket bolt for larger frames and corrosion resistance.", optionValues: { threadSize: "M10", length: "40 mm", finish: "Zinc Plated" }, stock: "Limited stock", note: "Recommended for exposed surfaces.", modelShape: "cylinder", modelColor: "#94a3b8", modelAccent: "#eab308", modelScale: 1.08 }),
    ],
  }),
  createProduct({
    id: "fs-washer",
    categoryId: "fasteners",
    name: "Flat Washer SUS304 M10",
    description: "Stainless washer for load spreading and corrosion resistance in fastening joints.",
    type: "Washer",
    brand: "TorqueX",
    stock: "Limited stock",
    availability: "limited",
    image: "WS",
    selectors: [
      { key: "innerDiameter", label: "Inner Diameter", options: ["M8", "M10", "M12"] },
      { key: "outerDiameter", label: "Outer Diameter", options: ["16 mm", "20 mm", "24 mm"] },
      { key: "grade", label: "Material Grade", options: ["SUS304", "SUS316"] },
    ],
    variants: [
      variant({ sku: "FW-M8-16-304", price: 4, spec: "SUS304 washer for M8 bolts with 16 mm outside diameter.", optionValues: { innerDiameter: "M8", outerDiameter: "16 mm", grade: "SUS304" }, stock: "In stock", note: "Good for standard indoor machine panels.", modelShape: "torus", modelColor: "#cbd5e1", modelAccent: "#94a3b8", modelScale: 0.88 }),
      variant({ sku: "FW-M10-20-304", price: 6, spec: "SUS304 washer for M10 bolts with balanced load distribution.", optionValues: { innerDiameter: "M10", outerDiameter: "20 mm", grade: "SUS304" }, stock: "Limited stock", note: "Common size for machine and frame joints.", modelShape: "torus", modelColor: "#94a3b8", modelAccent: "#f97316", modelScale: 0.94 }),
      variant({ sku: "FW-M12-24-316", price: 11, spec: "SUS316 washer for M12 bolts in humid or chemical-prone zones.", optionValues: { innerDiameter: "M12", outerDiameter: "24 mm", grade: "SUS316" }, stock: "Preorder", note: "Best for harsh environments and washdown equipment.", modelShape: "torus", modelColor: "#64748b", modelAccent: "#22c55e", modelScale: 1 }),
    ],
  }),
  createProduct({
    id: "lm-guide",
    categoryId: "linear-motion",
    name: "Linear Guide Rail 20 Series",
    description: "Precision rail set for repeatable linear movement and stable machine motion.",
    type: "Guide Rail",
    brand: "LinearOne",
    stock: "In stock",
    availability: "in-stock",
    image: "LG",
    selectors: [
      { key: "railLength", label: "Rail Length", options: ["500 mm", "1000 mm", "1500 mm"] },
      { key: "blockType", label: "Block Type", options: ["Standard", "Flange"] },
      { key: "accuracy", label: "Accuracy Grade", options: ["Normal", "High"] },
    ],
    variants: [
      variant({ sku: "LGR20-500-ST-N", price: 1890, spec: "500 mm linear rail with standard block and normal accuracy.", optionValues: { railLength: "500 mm", blockType: "Standard", accuracy: "Normal" }, stock: "In stock", note: "Good starting point for compact jigs.", modelShape: "capsule", modelColor: "#475569", modelAccent: "#f59e0b", modelScale: 0.95 }),
      variant({ sku: "LGR20-1000-ST-H", price: 2490, spec: "1000 mm rail with standard block and high accuracy for automation.", optionValues: { railLength: "1000 mm", blockType: "Standard", accuracy: "High" }, stock: "In stock", note: "Balanced option for machine axes.", modelShape: "capsule", modelColor: "#334155", modelAccent: "#38bdf8", modelScale: 1.05 }),
      variant({ sku: "LGR20-1500-FL-H", price: 3390, spec: "1500 mm flange-block rail for larger load support and precision travel.", optionValues: { railLength: "1500 mm", blockType: "Flange", accuracy: "High" }, stock: "Preorder", note: "Recommended for wider gantry designs.", modelShape: "capsule", modelColor: "#0f172a", modelAccent: "#22c55e", modelScale: 1.15 }),
    ],
  }),
  createProduct({
    id: "lm-ball-screw",
    categoryId: "linear-motion",
    name: "Precision Ball Screw 1605",
    description: "Ball screw set for motion control, lifting stages, and linear actuators.",
    type: "Ball Screw",
    brand: "LinearOne",
    stock: "Preorder",
    availability: "preorder",
    image: "BS",
    selectors: [
      { key: "diameterLead", label: "Diameter / Lead", options: ["1204", "1605", "2005"] },
      { key: "shaftLength", label: "Shaft Length", options: ["300 mm", "600 mm", "1000 mm"] },
      { key: "nutType", label: "Nut Type", options: ["Single Nut", "Double Nut"] },
    ],
    variants: [
      variant({ sku: "BS-1204-300-SN", price: 2190, spec: "12 mm screw with 4 mm lead for compact positioning systems.", optionValues: { diameterLead: "1204", shaftLength: "300 mm", nutType: "Single Nut" }, stock: "In stock", note: "Smooth choice for light desktop automation.", modelShape: "cylinder", modelColor: "#94a3b8", modelAccent: "#6366f1", modelScale: 0.92 }),
      variant({ sku: "BS-1605-600-SN", price: 3580, spec: "16 mm screw with 5 mm lead for standard motion modules.", optionValues: { diameterLead: "1605", shaftLength: "600 mm", nutType: "Single Nut" }, stock: "Preorder", note: "Good balance of speed and rigidity.", modelShape: "cylinder", modelColor: "#475569", modelAccent: "#38bdf8", modelScale: 1 }),
      variant({ sku: "BS-2005-1000-DN", price: 4890, spec: "20 mm screw with double nut for better preload and long travel support.", optionValues: { diameterLead: "2005", shaftLength: "1000 mm", nutType: "Double Nut" }, stock: "Preorder", note: "Better for heavier machine tables.", modelShape: "cylinder", modelColor: "#0f172a", modelAccent: "#22c55e", modelScale: 1.12 }),
    ],
  }),
  createProduct({
    id: "pn-cylinder",
    categoryId: "pneumatic-components",
    name: "Compact Air Cylinder SDA 32x50",
    description: "Compact cylinder for constrained mounting spaces and repetitive actuator tasks.",
    type: "Cylinder",
    brand: "AirNova",
    stock: "In stock",
    availability: "in-stock",
    image: "AC",
    selectors: [
      { key: "bore", label: "Bore Size", options: ["20 mm", "32 mm", "40 mm"] },
      { key: "stroke", label: "Stroke", options: ["25 mm", "50 mm", "75 mm"] },
      { key: "sensor", label: "Sensor Ready", options: ["No", "Yes"] },
    ],
    variants: [
      variant({ sku: "SDA20-25-N", price: 790, spec: "Compact cylinder with 20 mm bore and 25 mm stroke.", optionValues: { bore: "20 mm", stroke: "25 mm", sensor: "No" }, stock: "In stock", note: "Short-stroke option for clamping motions.", modelShape: "capsule", modelColor: "#e5e7eb", modelAccent: "#38bdf8", modelScale: 0.9 }),
      variant({ sku: "SDA32-50-Y", price: 1180, spec: "32 mm bore compact cylinder with 50 mm stroke and sensor groove.", optionValues: { bore: "32 mm", stroke: "50 mm", sensor: "Yes" }, stock: "In stock", note: "Popular size for pick-and-place tooling.", modelShape: "capsule", modelColor: "#cbd5e1", modelAccent: "#f97316", modelScale: 1 }),
      variant({ sku: "SDA40-75-Y", price: 1490, spec: "40 mm bore cylinder with longer stroke for higher push distance.", optionValues: { bore: "40 mm", stroke: "75 mm", sensor: "Yes" }, stock: "Limited stock", note: "Useful for end-of-line pneumatic tooling.", modelShape: "capsule", modelColor: "#94a3b8", modelAccent: "#22c55e", modelScale: 1.1 }),
    ],
  }),
  createProduct({
    id: "pn-valve",
    categoryId: "pneumatic-components",
    name: "5/2 Solenoid Valve 24VDC",
    description: "Directional valve for controlling cylinders and air-driven actuators.",
    type: "Valve",
    brand: "AirNova",
    stock: "In stock",
    availability: "in-stock",
    image: "SV",
    selectors: [
      { key: "portSize", label: "Port Size", options: ["1/8", "1/4", "3/8"] },
      { key: "coilVoltage", label: "Coil Voltage", options: ["12VDC", "24VDC", "220VAC"] },
      { key: "bodyType", label: "Body Type", options: ["Inline", "Manifold"] },
    ],
    variants: [
      variant({ sku: "SV52-18-12-IN", price: 760, spec: "1/8 port valve with 12VDC coil for compact pneumatic panels.", optionValues: { portSize: "1/8", coilVoltage: "12VDC", bodyType: "Inline" }, stock: "In stock", note: "Great for compact benches and small actuators.", modelShape: "box", modelColor: "#1f2937", modelAccent: "#22c55e", modelScale: 0.9 }),
      variant({ sku: "SV52-14-24-MF", price: 920, spec: "1/4 port manifold-ready valve with 24VDC coil for standard automation.", optionValues: { portSize: "1/4", coilVoltage: "24VDC", bodyType: "Manifold" }, stock: "In stock", note: "Matches common PLC output systems.", modelShape: "box", modelColor: "#111827", modelAccent: "#f97316", modelScale: 1 }),
      variant({ sku: "SV52-38-220-IN", price: 1290, spec: "3/8 port inline valve with 220VAC coil for larger airflow demand.", optionValues: { portSize: "3/8", coilVoltage: "220VAC", bodyType: "Inline" }, stock: "Preorder", note: "Useful for higher flow consumption points.", modelShape: "box", modelColor: "#374151", modelAccent: "#38bdf8", modelScale: 1.12 }),
    ],
  }),
  createProduct({
    id: "el-psu",
    categoryId: "electrical-components",
    name: "DIN Rail Power Supply 24V 5A",
    description: "Stable DIN rail power supply for control cabinets and machine circuits.",
    type: "Power Supply",
    brand: "VoltEdge",
    stock: "In stock",
    availability: "in-stock",
    image: "PS",
    selectors: [
      { key: "output", label: "Output Rating", options: ["24V 2.5A", "24V 5A", "24V 10A"] },
      { key: "inputRange", label: "Input Range", options: ["1-phase 220VAC", "1-phase 110-240VAC"] },
      { key: "redundancy", label: "Redundancy Ready", options: ["No", "Yes"] },
    ],
    variants: [
      variant({ sku: "PSU-24-2P5A-220-N", price: 980, spec: "Compact 24V 2.5A supply for small panels and sensors.", optionValues: { output: "24V 2.5A", inputRange: "1-phase 220VAC", redundancy: "No" }, stock: "In stock", note: "Fits narrow cabinets with light loads.", modelShape: "box", modelColor: "#f8fafc", modelAccent: "#38bdf8", modelScale: 0.88 }),
      variant({ sku: "PSU-24-5A-WIDE-N", price: 1340, spec: "24V 5A DIN supply with wide input range for general machine control.", optionValues: { output: "24V 5A", inputRange: "1-phase 110-240VAC", redundancy: "No" }, stock: "In stock", note: "Standard choice for mixed cabinet loads.", modelShape: "box", modelColor: "#e2e8f0", modelAccent: "#f97316", modelScale: 1 }),
      variant({ sku: "PSU-24-10A-WIDE-Y", price: 1980, spec: "24V 10A high-capacity supply with redundancy-ready output.", optionValues: { output: "24V 10A", inputRange: "1-phase 110-240VAC", redundancy: "Yes" }, stock: "Limited stock", note: "Recommended for critical control cabinets.", modelShape: "box", modelColor: "#cbd5e1", modelAccent: "#22c55e", modelScale: 1.12 }),
    ],
  }),
  createProduct({
    id: "el-relay",
    categoryId: "electrical-components",
    name: "General Purpose Relay 8 Pin",
    description: "Plug-in relay for basic switching and interlock circuits.",
    type: "Relay",
    brand: "VoltEdge",
    stock: "Limited stock",
    availability: "limited",
    image: "RL",
    selectors: [
      { key: "coilVoltage", label: "Coil Voltage", options: ["12VDC", "24VDC", "220VAC"] },
      { key: "contactForm", label: "Contact Form", options: ["2C", "4C"] },
      { key: "indicator", label: "Indicator", options: ["With LED", "Without LED"] },
    ],
    variants: [
      variant({ sku: "RLY-12-2C-LED", price: 165, spec: "12VDC relay with 2 changeover contacts and LED indicator.", optionValues: { coilVoltage: "12VDC", contactForm: "2C", indicator: "With LED" }, stock: "In stock", note: "Useful for compact low-voltage panels.", modelShape: "box", modelColor: "#1e293b", modelAccent: "#eab308", modelScale: 0.84 }),
      variant({ sku: "RLY-24-4C-LED", price: 215, spec: "24VDC relay with 4 changeover contacts and LED indicator.", optionValues: { coilVoltage: "24VDC", contactForm: "4C", indicator: "With LED" }, stock: "Limited stock", note: "Best fit for PLC interlock circuits.", modelShape: "box", modelColor: "#0f172a", modelAccent: "#38bdf8", modelScale: 0.92 }),
      variant({ sku: "RLY-220-4C-NOLED", price: 248, spec: "220VAC relay with 4 contacts for direct AC control usage.", optionValues: { coilVoltage: "220VAC", contactForm: "4C", indicator: "Without LED" }, stock: "Preorder", note: "Chosen when direct AC coil operation is needed.", modelShape: "box", modelColor: "#334155", modelAccent: "#22c55e", modelScale: 0.96 }),
    ],
  }),
  createProduct({
    id: "tool-torque",
    categoryId: "tools",
    name: "Adjustable Torque Wrench 5-25Nm",
    description: "Torque wrench for controlled tightening during equipment assembly.",
    type: "Hand Tool",
    brand: "ForgeLab",
    stock: "In stock",
    availability: "in-stock",
    image: "TW",
    selectors: [
      { key: "range", label: "Torque Range", options: ["5-25 Nm", "10-60 Nm", "20-100 Nm"] },
      { key: "drive", label: "Drive Size", options: ['1/4"', '3/8"', '1/2"'] },
      { key: "certificate", label: "Calibration", options: ["Standard", "Certified"] },
    ],
    variants: [
      variant({ sku: 'TW-525-14-ST', price: 1780, spec: '5-25 Nm wrench with 1/4" drive for precision assembly.', optionValues: { range: "5-25 Nm", drive: '1/4"', certificate: "Standard" }, stock: "In stock", note: "Ideal for sensor brackets and compact fasteners.", modelShape: "cylinder", modelColor: "#334155", modelAccent: "#f97316", modelScale: 0.95 }),
      variant({ sku: 'TW-1060-38-CF', price: 2290, spec: '10-60 Nm wrench with 3/8" drive and calibration certificate.', optionValues: { range: "10-60 Nm", drive: '3/8"', certificate: "Certified" }, stock: "In stock", note: "Great fit for machine frame assembly.", modelShape: "cylinder", modelColor: "#0f172a", modelAccent: "#38bdf8", modelScale: 1.02 }),
      variant({ sku: 'TW-20100-12-CF', price: 2990, spec: '20-100 Nm wrench with 1/2" drive for higher torque joints.', optionValues: { range: "20-100 Nm", drive: '1/2"', certificate: "Certified" }, stock: "Limited stock", note: "Recommended for structural fastening and maintenance.", modelShape: "cylinder", modelColor: "#111827", modelAccent: "#22c55e", modelScale: 1.08 }),
    ],
  }),
  createProduct({
    id: "tool-caliper",
    categoryId: "tools",
    name: "Digital Caliper 150mm",
    description: "Digital measuring tool for inspection, setup, and dimensional checks.",
    type: "Measuring Tool",
    brand: "ForgeLab",
    stock: "In stock",
    availability: "in-stock",
    image: "CL",
    selectors: [
      { key: "measurementRange", label: "Measurement Range", options: ["150 mm", "200 mm", "300 mm"] },
      { key: "resolution", label: "Resolution", options: ["0.01 mm", "0.02 mm"] },
      { key: "protection", label: "Protection Class", options: ["Standard", "IP54"] },
    ],
    variants: [
      variant({ sku: "DC-150-001-ST", price: 740, spec: "150 mm caliper with 0.01 mm resolution for standard workshop inspection.", optionValues: { measurementRange: "150 mm", resolution: "0.01 mm", protection: "Standard" }, stock: "In stock", note: "Most common setup for bench use.", modelShape: "capsule", modelColor: "#cbd5e1", modelAccent: "#38bdf8", modelScale: 0.94 }),
      variant({ sku: "DC-200-001-IP54", price: 980, spec: "200 mm caliper with IP54 protection for production floor measurements.", optionValues: { measurementRange: "200 mm", resolution: "0.01 mm", protection: "IP54" }, stock: "In stock", note: "Good fit for coolant or dusty areas.", modelShape: "capsule", modelColor: "#94a3b8", modelAccent: "#f97316", modelScale: 1 }),
      variant({ sku: "DC-300-002-IP54", price: 1490, spec: "300 mm caliper with 0.02 mm resolution for larger workpieces.", optionValues: { measurementRange: "300 mm", resolution: "0.02 mm", protection: "IP54" }, stock: "Preorder", note: "Better for long fixture and frame checks.", modelShape: "capsule", modelColor: "#475569", modelAccent: "#22c55e", modelScale: 1.08 }),
    ],
  }),
  createProduct({
    id: "af-profile",
    categoryId: "aluminum-frames",
    name: "Aluminum Profile 4040 T-Slot",
    description: "Extrusion profile for modular structures, workstations, and machine bases.",
    type: "Profile",
    brand: "FrameWorks",
    stock: "In stock",
    availability: "in-stock",
    image: "40",
    selectors: [
      { key: "section", label: "Section Size", options: ["2020", "3030", "4040"] },
      { key: "length", label: "Cut Length", options: ["500 mm", "1000 mm", "2000 mm"] },
      { key: "surface", label: "Surface Finish", options: ["Mill", "Anodized"] },
    ],
    variants: [
      variant({ sku: "AF-2020-500-ML", price: 180, spec: "2020 profile cut to 500 mm for light frames and sensor stands.", optionValues: { section: "2020", length: "500 mm", surface: "Mill" }, stock: "In stock", note: "Entry option for lightweight builds.", modelShape: "box", modelColor: "#d4d4d8", modelAccent: "#f59e0b", modelScale: 0.9 }),
      variant({ sku: "AF-4040-1000-AN", price: 560, spec: "4040 anodized profile, 1000 mm length, for machine and bench frames.", optionValues: { section: "4040", length: "1000 mm", surface: "Anodized" }, stock: "In stock", note: "Standard selection for rigid structures.", modelShape: "box", modelColor: "#a1a1aa", modelAccent: "#38bdf8", modelScale: 1.05 }),
      variant({ sku: "AF-4040-2000-AN", price: 1040, spec: "4040 anodized profile in 2000 mm stock for longer machine spans.", optionValues: { section: "4040", length: "2000 mm", surface: "Anodized" }, stock: "Preorder", note: "Useful for conveyor frames and gantries.", modelShape: "box", modelColor: "#71717a", modelAccent: "#22c55e", modelScale: 1.15 }),
    ],
  }),
  createProduct({
    id: "af-bracket",
    categoryId: "aluminum-frames",
    name: "Corner Bracket Set 4040",
    description: "Corner bracket for quickly joining aluminum profiles at right angles.",
    type: "Bracket",
    brand: "FrameWorks",
    stock: "In stock",
    availability: "in-stock",
    image: "CB",
    selectors: [
      { key: "profileSize", label: "Profile Size", options: ["2020", "3030", "4040"] },
      { key: "bracketType", label: "Bracket Type", options: ["Single", "Double"] },
      { key: "finish", label: "Finish", options: ["Silver", "Black"] },
    ],
    variants: [
      variant({ sku: "CB-2020-S-S", price: 54, spec: "Single corner bracket for 2020 profiles in silver finish.", optionValues: { profileSize: "2020", bracketType: "Single", finish: "Silver" }, stock: "In stock", note: "Small-format framing connections.", modelShape: "cone", modelColor: "#d4d4d8", modelAccent: "#f97316", modelScale: 0.84 }),
      variant({ sku: "CB-4040-S-B", price: 128, spec: "Single 4040 corner bracket in black anodized finish.", optionValues: { profileSize: "4040", bracketType: "Single", finish: "Black" }, stock: "In stock", note: "Clean look for exposed machine frames.", modelShape: "cone", modelColor: "#334155", modelAccent: "#38bdf8", modelScale: 1 }),
      variant({ sku: "CB-4040-D-B", price: 198, spec: "Double-support 4040 corner bracket for higher joint rigidity.", optionValues: { profileSize: "4040", bracketType: "Double", finish: "Black" }, stock: "Limited stock", note: "Best for load-bearing frame corners.", modelShape: "cone", modelColor: "#0f172a", modelAccent: "#22c55e", modelScale: 1.08 }),
    ],
  }),
  createProduct({
    id: "sn-photo",
    categoryId: "sensors",
    name: "Photoelectric Sensor Diffuse Type",
    description: "Diffuse sensor for detecting parts and presence over short to medium ranges.",
    type: "Photoelectric",
    brand: "SenseCore",
    stock: "In stock",
    availability: "in-stock",
    image: "PE",
    selectors: [
      { key: "sensingDistance", label: "Sensing Distance", options: ["100 mm", "300 mm", "500 mm"] },
      { key: "output", label: "Output Type", options: ["NPN", "PNP"] },
      { key: "cable", label: "Connection", options: ["Cable", "M8 Connector"] },
    ],
    variants: [
      variant({ sku: "PES-100-N-CB", price: 820, spec: "Diffuse sensor with 100 mm range and fixed cable output.", optionValues: { sensingDistance: "100 mm", output: "NPN", cable: "Cable" }, stock: "In stock", note: "Faster response for close-range inspection.", modelShape: "box", modelColor: "#f59e0b", modelAccent: "#0f172a", modelScale: 0.84 }),
      variant({ sku: "PES-300-P-M8", price: 980, spec: "300 mm sensor with PNP output and M8 quick connector.", optionValues: { sensingDistance: "300 mm", output: "PNP", cable: "M8 Connector" }, stock: "In stock", note: "Popular option for modular machine wiring.", modelShape: "box", modelColor: "#f97316", modelAccent: "#38bdf8", modelScale: 0.94 }),
      variant({ sku: "PES-500-P-M8", price: 1180, spec: "500 mm diffuse sensor for larger working envelopes.", optionValues: { sensingDistance: "500 mm", output: "PNP", cable: "M8 Connector" }, stock: "Limited stock", note: "Useful for conveyors and box detection.", modelShape: "box", modelColor: "#ea580c", modelAccent: "#22c55e", modelScale: 1 }),
    ],
  }),
  createProduct({
    id: "sn-proximity",
    categoryId: "sensors",
    name: "Inductive Proximity Sensor M12",
    description: "Metal detection sensor for positioning and presence sensing in automation cells.",
    type: "Proximity",
    brand: "SenseCore",
    stock: "Limited stock",
    availability: "limited",
    image: "PX",
    selectors: [
      { key: "bodySize", label: "Body Size", options: ["M8", "M12", "M18"] },
      { key: "sensingRange", label: "Sensing Range", options: ["2 mm", "4 mm", "8 mm"] },
      { key: "output", label: "Output Type", options: ["NPN NO", "PNP NO"] },
    ],
    variants: [
      variant({ sku: "IPS-M8-2-NPN", price: 520, spec: "Compact M8 proximity sensor with 2 mm sensing range.", optionValues: { bodySize: "M8", sensingRange: "2 mm", output: "NPN NO" }, stock: "In stock", note: "Tight-space mounting with short detection range.", modelShape: "cylinder", modelColor: "#475569", modelAccent: "#38bdf8", modelScale: 0.82 }),
      variant({ sku: "IPS-M12-4-PNP", price: 650, spec: "M12 inductive sensor with 4 mm range and PNP NO output.", optionValues: { bodySize: "M12", sensingRange: "4 mm", output: "PNP NO" }, stock: "Limited stock", note: "Standard selection for general factory automation.", modelShape: "cylinder", modelColor: "#334155", modelAccent: "#f97316", modelScale: 0.92 }),
      variant({ sku: "IPS-M18-8-PNP", price: 860, spec: "Larger M18 sensor with 8 mm range for robust metal detection.", optionValues: { bodySize: "M18", sensingRange: "8 mm", output: "PNP NO" }, stock: "Preorder", note: "Recommended for wider gaps and harsher layouts.", modelShape: "cylinder", modelColor: "#0f172a", modelAccent: "#22c55e", modelScale: 1.04 }),
    ],
  }),
  createProduct({
    id: "at-plc",
    categoryId: "automation-parts",
    name: "Compact PLC Starter Unit",
    description: "Compact PLC package for building small automation systems and training rigs.",
    type: "Controller",
    brand: "AutoGrid",
    stock: "In stock",
    availability: "in-stock",
    image: "PLC",
    selectors: [
      { key: "ioCount", label: "I/O Count", options: ["12 I/O", "24 I/O", "40 I/O"] },
      { key: "communication", label: "Communication", options: ["USB", "Ethernet", "Ethernet + RS485"] },
      { key: "memory", label: "Program Memory", options: ["Basic", "Standard", "Extended"] },
    ],
    variants: [
      variant({ sku: "PLC-12-USB-B", price: 3890, spec: "12 I/O compact PLC with USB programming for starter projects.", optionValues: { ioCount: "12 I/O", communication: "USB", memory: "Basic" }, stock: "In stock", note: "Good first controller for small cells and labs.", modelShape: "box", modelColor: "#111827", modelAccent: "#eab308", modelScale: 0.9 }),
      variant({ sku: "PLC-24-ETH-S", price: 5290, spec: "24 I/O PLC with Ethernet connectivity and standard memory.", optionValues: { ioCount: "24 I/O", communication: "Ethernet", memory: "Standard" }, stock: "In stock", note: "Most balanced choice for machine builders.", modelShape: "box", modelColor: "#0f172a", modelAccent: "#38bdf8", modelScale: 1 }),
      variant({ sku: "PLC-40-ERS-E", price: 6980, spec: "40 I/O PLC with Ethernet and RS485 plus extended program memory.", optionValues: { ioCount: "40 I/O", communication: "Ethernet + RS485", memory: "Extended" }, stock: "Preorder", note: "For larger lines with more device integration.", modelShape: "box", modelColor: "#1e293b", modelAccent: "#22c55e", modelScale: 1.12 }),
    ],
  }),
  createProduct({
    id: "at-coupling",
    categoryId: "automation-parts",
    name: "Servo Coupling Zero Backlash",
    description: "Zero-backlash coupling for servo drives, encoders, and motion transmission.",
    type: "Coupling",
    brand: "AutoGrid",
    stock: "Preorder",
    availability: "preorder",
    image: "CP",
    selectors: [
      { key: "borePair", label: "Bore Combination", options: ["6x8 mm", "8x10 mm", "10x14 mm"] },
      { key: "bodyStyle", label: "Body Style", options: ["Single Disc", "Double Disc"] },
      { key: "clamp", label: "Clamp Type", options: ["Set Screw", "Clamp"] },
    ],
    variants: [
      variant({ sku: "CP-68-SD-SS", price: 890, spec: "6x8 mm single-disc coupling with set-screw fixation.", optionValues: { borePair: "6x8 mm", bodyStyle: "Single Disc", clamp: "Set Screw" }, stock: "In stock", note: "Compact transfer between small motors and screws.", modelShape: "torus", modelColor: "#94a3b8", modelAccent: "#eab308", modelScale: 0.9 }),
      variant({ sku: "CP-810-DD-CL", price: 1180, spec: "8x10 mm double-disc clamp coupling for smooth servo response.", optionValues: { borePair: "8x10 mm", bodyStyle: "Double Disc", clamp: "Clamp" }, stock: "Preorder", note: "Good balance of compliance and precision.", modelShape: "torus", modelColor: "#64748b", modelAccent: "#38bdf8", modelScale: 1 }),
      variant({ sku: "CP-1014-DD-CL", price: 1490, spec: "10x14 mm double-disc coupling for higher torque transmission.", optionValues: { borePair: "10x14 mm", bodyStyle: "Double Disc", clamp: "Clamp" }, stock: "Preorder", note: "Better fit for larger servo axes.", modelShape: "torus", modelColor: "#334155", modelAccent: "#22c55e", modelScale: 1.08 }),
    ],
  }),
];

export function getDefaultVariant(product) {
  return product.variants[0];
}

export function findVariant(product, selectedOptions) {
  return (
    product.variants.find((item) =>
      product.selectors.every((selector) => item.optionValues[selector.key] === selectedOptions[selector.key]),
    ) || product.variants[0]
  );
}

export const formatPrice = (value) =>
  new Intl.NumberFormat("th-TH", {
    style: "currency",
    currency: "THB",
    maximumFractionDigits: 0,
  }).format(value);
